"""Report model embedded as source, generated by scripts/build_submission.py.

Do not edit by hand. This is a module rather than a data file on purpose: the
platform mounts its own volume over /opt/ml/model, and an import cannot be
shadowed by a mount.

Constant report: 13 statements, FINAL 0.3999 (RadFact P 0.470 R 0.416, BLEU 0.1157, METEOR 0.3524).
Adaptive report: 8 core + 5 gated statements, FINAL 0.4122 (RadFact P 0.522 R 0.405, BLEU 0.1268, METEOR 0.3431).
"""

from __future__ import annotations

CONSTANT_REPORT = 'Mandibular CT including within the acquisition volume the mandibular body and excluding the coronoid and condylar processes. Maxilla: not included. Mandibular condyles are not included in the scan. Mandible: mandibular canal with a predominantly lingual course, in close relationship with the roots of teeth 38 and 48. At the mandibular level, teeth 38 and 48 are semi-impacted with a vertical long axis. Composite conservative restorations are present on the occlusal surfaces of the crowns of teeth 36, 37, 46 and 47. Teeth 34, 35, 36, 45, 46 and 47 have been endodontically treated and have already undergone prosthetic reconstruction. Teeth from 48 to 38 in the arch. Tooth 48 is minimally extruded, mesioverted and impacting on the distal root of 47. A radiolucent area is present, possibly compatible with a post-extraction socket of the mesial root of tooth 36. The mandibular canal shows a predominantly lingual course on the right. The mandibular canals show a regular course bilaterally. The mandibular canal shows a course with predominantly lingual development, with regular cortical definition and without evident pathological relationships with the remaining teeth.'

ADAPTIVE = {
    "version": 1,
    "texts": [
        "Mandibular condyles are not included in the scan.",
        "Mandibular CT including within the acquisition volume the mandibular body and excluding the coronoid and condylar processes.",
        "Mandible: mandibular canal with a predominantly lingual course, in close relationship with the roots of teeth 38 and 48.",
        "Maxilla: not included.",
        "At the mandibular level, teeth 38 and 48 are semi-impacted with a vertical long axis.",
        "The mandibular canal shows a predominantly lingual course on the right.",
        "The mandibular canals show a regular course bilaterally.",
        "Composite conservative restorations are present on the occlusal surfaces of the crowns of teeth 36, 37, 46 and 47.",
        "Teeth 34, 35, 36, 45, 46 and 47 have been endodontically treated and have already undergone prosthetic reconstruction.",
        "Teeth from 48 to 38 in the arch.",
        "The mandibular canal shows a course with predominantly lingual development, with regular cortical definition and without evident pathological relationships with the remaining teeth.",
        "A radiolucent area is present, possibly compatible with a post-extraction socket of the mesial root of tooth 36.",
        "Tooth 48 is minimally extruded, mesioverted and impacting on the distal root of 47."
    ],
    "core": [
        0,
        7,
        8,
        9,
        11,
        5,
        6,
        10
    ],
    "conditional": [
        1,
        2,
        3,
        4,
        12
    ],
    "coefficients": [
        [
            -0.3748635908129621,
            -0.382770181176758,
            -0.11489233615543912,
            -0.30353595310537734,
            -0.07480487074061695,
            -0.07480487074061695,
            -0.6097155211306786,
            -0.22484509989157606,
            0.2105446514536987
        ],
        [
            -0.13097029631038656,
            -0.17888503853881216,
            -0.6851427667499834,
            -0.21095690572346332,
            0.29190048748416275,
            0.29190048748416275,
            0.14499525401114902,
            0.9548174242861409,
            0.5140905724155825
        ],
        [
            -0.9093821511919032,
            0.1642960251360583,
            0.17317261607525664,
            -0.36408276183350424,
            -0.10862293415871396,
            -0.10862293415871396,
            -2.047173894134058,
            -0.23933212130518364,
            -0.3113637553222764
        ],
        [
            -1.0754015399109533,
            0.4010874409371115,
            -1.0939525032689572,
            0.014981727269675537,
            0.017729973821005354,
            0.017729973821005354,
            -1.711195514155124,
            0.6944043285314585,
            -1.107243745729236
        ],
        [
            -0.040308422633619466,
            -0.018338525264744925,
            -1.0799875725589887,
            0.009795727264231132,
            0.28353598649936607,
            0.28353598649936607,
            0.4481854716486082,
            1.1224262274884327,
            -0.0017858877716766279
        ]
    ],
    "intercepts": [
        -0.29242377232033023,
        -0.7073987081035499,
        -0.94120406014029,
        -1.6787313309851029,
        -0.8986080972910114
    ],
    "thresholds": [
        0.4,
        0.3,
        0.4,
        0.5,
        0.3
    ],
    "mean": [
        5.336179021442251,
        5.904314946979958,
        5.9943017893568795,
        0.2844829560284446,
        0.28364694316143774,
        0.28364694316143774,
        4.0757249850829975,
        4.635159513586233,
        4.72454946990104
    ],
    "scale": [
        0.38296827774388986,
        0.19060022631759568,
        0.14521400739072554,
        0.04369028426359794,
        0.04391468285500459,
        0.04391468285500459,
        0.22763948170527074,
        0.13586433792098276,
        0.1261241159792361
    ],
    "order": [
        1,
        3,
        0,
        2,
        4,
        7,
        8,
        9,
        12,
        11,
        5,
        6,
        10
    ]
}
