"""Report model embedded as source, generated by scripts/build_submission.py.

Do not edit by hand. This is a module rather than a data file on purpose: the
platform mounts its own volume over /opt/ml/model, and an import cannot be
shadowed by a mount.

Constant report: 15 statements, FINAL 0.4177 (RadFact P 0.521 R 0.416, BLEU 0.1176, METEOR 0.3591).
Adaptive report: 10 core + 5 gated statements, FINAL 0.4288 (RadFact P 0.570 R 0.409, BLEU 0.1281, METEOR 0.3516).
"""

from __future__ import annotations

CONSTANT_REPORT = 'Mandibular CT including within the acquisition volume the mandibular body and excluding the coronoid and condylar processes. Maxilla: not included. Mandibular condyles are not included in the scan. Mandible: mandibular canal with a predominantly lingual course, in close relationship with the roots of teeth 38 and 48. Mandible: absence from the arch of teeth 35, 36, 37, 38, 48. At the mandibular level, teeth 38 and 48 are semi-impacted with a vertical long axis. It has undergone endodontic treatment with incongruent root canal therapy as it does not reach the dental apex. Composite conservative restorations are present on the occlusal surfaces of the crowns of teeth 36, 37, 46 and 47. 38 and 48 erupted in the arch. Mandible with severe bone atrophy and complete edentulism. Tooth 48 is minimally extruded, mesioverted and impacting on the distal root of 47. A prosthetic crown is present. The mandibular canal shows a predominantly lingual course on the right. Mandibular canal with a regular course and predominantly lingual position. The mandibular canals have an apico-lingual course bilaterally.'

ADAPTIVE = {
    "version": 1,
    "texts": [
        "Mandibular condyles are not included in the scan.",
        "Mandibular CT including within the acquisition volume the mandibular body and excluding the coronoid and condylar processes.",
        "Mandible: mandibular canal with a predominantly lingual course, in close relationship with the roots of teeth 38 and 48.",
        "Maxilla: not included.",
        "Mandible: absence from the arch of teeth 35, 36, 37, 38, 48.",
        "At the mandibular level, teeth 38 and 48 are semi-impacted with a vertical long axis.",
        "The mandibular canal shows a predominantly lingual course on the right.",
        "it has undergone endodontic treatment with incongruent root canal therapy as it does not reach the dental apex.",
        "Composite conservative restorations are present on the occlusal surfaces of the crowns of teeth 36, 37, 46 and 47.",
        "38 and 48 erupted in the arch.",
        "Mandible with severe bone atrophy and complete edentulism.",
        "Mandibular canal with a regular course and predominantly lingual position.",
        "The mandibular canals have an apico-lingual course bilaterally.",
        "Tooth 48 is minimally extruded, mesioverted and impacting on the distal root of 47.",
        "a prosthetic crown is present."
    ],
    "core": [
        0,
        4,
        7,
        8,
        9,
        10,
        14,
        6,
        11,
        12
    ],
    "conditional": [
        1,
        2,
        3,
        5,
        13
    ],
    "coefficients": [
        [
            -0.3748635908129621,
            -0.382770181176758,
            -0.11489233615543912,
            -0.30353595310537734,
            -0.07480487074061695,
            -0.07480487074061695,
            -0.6097155211306786,
            -0.22484509989157606,
            0.2105446514536987
        ],
        [
            -0.13097029631038656,
            -0.17888503853881216,
            -0.6851427667499834,
            -0.21095690572346332,
            0.29190048748416275,
            0.29190048748416275,
            0.14499525401114902,
            0.9548174242861409,
            0.5140905724155825
        ],
        [
            -0.9093821511919032,
            0.1642960251360583,
            0.17317261607525664,
            -0.36408276183350424,
            -0.10862293415871396,
            -0.10862293415871396,
            -2.047173894134058,
            -0.23933212130518364,
            -0.3113637553222764
        ],
        [
            -1.0754015399109533,
            0.4010874409371115,
            -1.0939525032689572,
            0.014981727269675537,
            0.017729973821005354,
            0.017729973821005354,
            -1.711195514155124,
            0.6944043285314585,
            -1.107243745729236
        ],
        [
            -0.040308422633619466,
            -0.018338525264744925,
            -1.0799875725589887,
            0.009795727264231132,
            0.28353598649936607,
            0.28353598649936607,
            0.4481854716486082,
            1.1224262274884327,
            -0.0017858877716766279
        ]
    ],
    "intercepts": [
        -0.29242377232033023,
        -0.7073987081035499,
        -0.94120406014029,
        -1.6787313309851029,
        -0.8986080972910114
    ],
    "thresholds": [
        0.4,
        0.3,
        0.4,
        0.3,
        0.3
    ],
    "mean": [
        5.336179021442251,
        5.904314946979958,
        5.9943017893568795,
        0.2844829560284446,
        0.28364694316143774,
        0.28364694316143774,
        4.0757249850829975,
        4.635159513586233,
        4.72454946990104
    ],
    "scale": [
        0.38296827774388986,
        0.19060022631759568,
        0.14521400739072554,
        0.04369028426359794,
        0.04391468285500459,
        0.04391468285500459,
        0.22763948170527074,
        0.13586433792098276,
        0.1261241159792361
    ],
    "order": [
        1,
        3,
        0,
        2,
        4,
        5,
        7,
        8,
        9,
        10,
        13,
        14,
        6,
        11,
        12
    ]
}
