"""Generate the submission's embedded report model.

The 16th-place submission scored 0.0161 because Grand Challenge mounts its own
volume at ``/opt/ml/model``, shadowing the bundle baked into the image. The fix
then was to bake the bundle at a second path; the fix here is stronger — the
report model is written into a *Python module* that ships next to
``inference.py``, so serving a case-adaptive report requires reading no data
file at all. A mount cannot shadow an import.

The module carries two things:

``CONSTANT_REPORT``
    The statement set that maximizes the challenge Final Score
    (``0.8 x RadFact + 0.2 x captioning``) as a single report for every case.
    This is the floor, and it is already better than anything reachable by
    tuning the visible leaderboard's captioning half.

``ADAPTIVE``
    Logistic gates over nine header-derived numbers, so statements about what
    the field of view contains are emitted only for the cases where they hold.

``inference.py`` prefers ``ADAPTIVE``, falls back to ``CONSTANT_REPORT``, and
falls back again to a copy embedded in ``inference.py`` itself.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

HEADER = '''"""Report model embedded as source, generated by scripts/build_submission.py.

Do not edit by hand. This is a module rather than a data file on purpose: the
platform mounts its own volume over /opt/ml/model, and an import cannot be
shadowed by a mount.

{provenance}
"""

from __future__ import annotations

CONSTANT_REPORT = {constant!r}

ADAPTIVE = {adaptive}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--adaptive", default="artifacts/adaptive_report.json")
    parser.add_argument("--constant", default="artifacts/final_score_report.json")
    parser.add_argument("--out", default="submission/report_model.py")
    args = parser.parse_args()

    constant_path = REPO_ROOT / args.constant
    if not constant_path.is_file():
        print(f"missing {constant_path}; run scripts/optimize_final_score.py first")
        return 1
    constant_payload = json.loads(constant_path.read_text(encoding="utf-8"))
    constant = " ".join(constant_payload["report"].split()).strip()

    provenance = [
        "Constant report: {} statements, FINAL {:.4f} "
        "(RadFact P {:.3f} R {:.3f}, BLEU {:.4f}, METEOR {:.4f}).".format(
            constant_payload.get("statements", 0),
            constant_payload.get("final", 0.0),
            constant_payload.get("logical_precision", 0.0),
            constant_payload.get("logical_recall", 0.0),
            constant_payload.get("bleu_4", 0.0),
            constant_payload.get("meteor", 0.0),
        )
    ]

    adaptive_path = REPO_ROOT / args.adaptive
    if adaptive_path.is_file():
        adaptive_payload = json.loads(adaptive_path.read_text(encoding="utf-8"))
        # Only the statements the model can actually emit are kept, so the module
        # does not carry the whole 989-entry prototype bank into the image.
        used = sorted(set(adaptive_payload["core"]) | set(adaptive_payload["conditional"]))
        remap = {old: new for new, old in enumerate(used)}
        adaptive_payload = {
            "version": adaptive_payload["version"],
            "texts": [adaptive_payload["texts"][i] for i in used],
            "core": [remap[i] for i in adaptive_payload["core"]],
            "conditional": [remap[i] for i in adaptive_payload["conditional"]],
            "coefficients": adaptive_payload["coefficients"],
            "intercepts": adaptive_payload["intercepts"],
            "thresholds": adaptive_payload["thresholds"],
            "mean": adaptive_payload["mean"],
            "scale": adaptive_payload["scale"],
            "order": [remap[i] for i in adaptive_payload["order"] if i in remap],
        }
        metrics_path = REPO_ROOT / "artifacts/adaptive_report_metrics.json"
        if metrics_path.is_file():
            metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
            provenance.append(
                "Adaptive report: {} core + {} gated statements, FINAL {:.4f} "
                "(RadFact P {:.3f} R {:.3f}, BLEU {:.4f}, METEOR {:.4f}).".format(
                    metrics.get("core", 0),
                    metrics.get("gated", 0),
                    metrics.get("final", 0.0),
                    metrics.get("logical_precision", 0.0),
                    metrics.get("logical_recall", 0.0),
                    metrics.get("bleu_4", 0.0),
                    metrics.get("meteor", 0.0),
                )
            )
        adaptive = json.dumps(adaptive_payload, indent=4, ensure_ascii=False)
    else:
        adaptive = "None"
        provenance.append("No adaptive report fitted; the constant report is the only path.")

    destination = REPO_ROOT / args.out
    destination.write_text(
        HEADER.format(
            provenance="\n".join(provenance),
            constant=constant,
            adaptive=adaptive,
        ),
        encoding="utf-8",
    )
    size = destination.stat().st_size
    print(f"wrote {destination} ({size / 1024:.1f} KB)")
    for line in provenance:
        print(f"  {line}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
